# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@4042d3876fbba3e76b95c16a18830ab0c152aeec
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
        # Remote host
        REMOTE_HOST: "139.196.49.192"
        # Remote user
        REMOTE_USER: "root"
        # Source directory
        SOURCE: "dist/"
        # Target directory
        TARGET: "/www/wwwroot/whj/"
        # Arguments to pass to rsync
        ARGS:  "-rltgoDzvO --delete"
#     - name: Deploy
#       uses: easingthemes/ssh-deploy@v2.0.7
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
#         ARGS: "-rltgoDzvO --delete"
#         SOURCE: "dist/"
#         REMOTE_HOST: "139.196.49.192"
#         REMOTE_USER: "root"
#         TARGET: "/www/wwwroot/whj/"
      
